# -*- coding: utf-8 -*-
{
    "name": "GoExcel Logistics SQ",
    "version": "12.0.2.0.4",
    "category": "Transport",
    "license": "LGPL-3",
    "summary": """Sales Quotation Enhancement""",
    "description": "Sales Quotation Enhancement",
    "author": "Excelroot Technology Sdn Bhd",
    "depends": ["sale_management", "sci_goexcel_freight"],
    "sequence": 2,
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "reports/report_sq_inherit.xml",
        "views/sales_quotation_view.xml",
        "views/res_config_settings_view.xml",
        "views/sale_order_template.xml",
        "views/res_users_view.xml",
        "views/sale_link_view.xml",
        "views/lcl_settings_view.xml",
        "views/sales_quotation_web_templates.xml",
        "data/edit_quotation_mail_template.xml",
        "data/confirm_quotation_mail_template.xml",
        "data/sq_mail_template_bl.xml",
        "data/quotation_mail_template.xml",
        "data/menu.xml",
        #"reports/report_sq_inherit.xml",
    ],
}
