{
    "name": "GoExcel Transport",
    "version": "12.0.2.0.3",
    "category": "Transport",
    "license": 'LGPL-3',
    "summary": """Transport Management System for Freight""",
    'description': 'Transport Management System for Freight',
    "author": "Excelroot Technology Sdn Bhd",
    "depends": ['product', 'account', 'sale', 'mail', 'sci_goexcel_freight', 'fleet', 'web_widget_digitized_signature'
        , 'web_timeline','hr', 'web_tree_dynamic_colored_field'],
    'sequence': 2,
    'application': True,
    "data": [
        'security/transport_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'wizards/pod_signature.xml',
        'wizards/assign_ltl.xml',
        'report/rft.xml',
        'report/delivery_order.xml',
        'report/door_to_door_delivery_order.xml',
        'views/invoice_wizard.xml',
        'views/transport_rft_view.xml',
        'views/sales_quotation_view.xml',
        'views/freight_booking_view.xml',
        'views/configure_view.xml',
        'views/res_partner_view.xml',
        'views/cron.xml',
        'views/invoice_view.xml',
        'views/res_config_settings_view.xml',
        'views/fleet_view.xml',
        'views/dispatch_trip_view.xml',
        'data/mail_template.xml',
        'data/do_mail_template.xml',

    ],
}