from . import sale_order
from . import product
from . import res_partner
from . import res_company
from . import res_config
from . import crm_order_line
from . import technical_suppoprt
from . import stock_picking
from . import res_users
from . import account_invoice
