from . import booking_invoice_line
from . import booking_inherit
from . import bol_inherit
from . import account_invoice
from . import invoice_wizard_inherit
from . import res_partner
from . import sales_quotation_inherit
from . import res_users
from . import si_inherit
from . import res_config_settings
from . import product_template
from . import sale_term_inherit
from . import sale_order_template_inherit
from . import product_pricelist
from . import invoice_booking_report
