from . import attendance_report_config
from . import hr_attendance
from . import hr_attendance_overtime
from . import hr_attendance_sheet
from . import hr_employee
from . import location_data
from . import res_company
from . import res_config_settings
from . import res_groups