# -*- coding: utf-8 -*-
{
    "name": "GoExcel Logistics Master Job",
    "version": "12.0.1.0.0",
    "category": "Transport",
    "license": "LGPL-3",
    "summary": """GoExcel Logistics Master Job""",
    "description": "GoExcel Logistics Master Job",
    "author": "Excelroot Technology Sdn Bhd",
    "depends": [
        "base",
        "sci_goexcel_freight",
        "sci_goexcel_freight_2",
        "sci_goexcel_transport",
        "sale_management",
        "account",
        "mail",
    ],
    "sequence": 2,
    "application": True,
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/shipment_term.xml",
        "data/cargo_type.xml",
        "views/master_booking_transport_view.xml",
        "views/booking_view.xml",
        'wizards/copy_booking_wizard_view.xml',
        #'views/master_booking_join_view.xml',
        "views/sales_quotation_view.xml",
        "views/res_partner_view.xml",
        #'views/booking_invoice_report.xml',
        #'views/booking_cost_profit_report.xml',
    ],
}
